POST https://api.ap3api.com/v1/ecommerce/event
Content-Type: application/json
X-Api-Key: PRV-customecommerce-1shR82MB-CTlwRWHRrSJLFL8qvdgbJlucXZl5vmBwvg

{
    "events": [
        {
            "resource": "product",
            "event": "deleted",
            "data_source_id": "62327644b185efab5195e842",
            "data": { "id": "113", "variant_id": "", "updated_at": "2022-03-21T01:36:46Z" }
}
    ],
    "async": false
}

###
GET https://api.bigcommerce.com/stores/h98d0e4glr/v3/carts/5d978238-1552-4932-be07-cfa2c8cc195b?include=line_items.physical_items.options
Content-Type: application/json
X-Auth-Token: 7kiueoy9m6jwqq3xtonlqmoifrij1w5

###
GET https://api.bigcommerce.com/stores/h98d0e4glr/v3/checkouts/5d978238-1552-4932-be07-cfa2c8cc195b?include=cart.line_items.physical_items.options
Content-Type: application/json
X-Auth-Token: 7kiueoy9m6jwqq3xtonlqmoifrij1w5


###
GET https://api.bigcommerce.com/stores/h98d0e4glr/v3/hooks
Content-Type: application/json
X-Auth-Token: 7kiueoy9m6jwqq3xtonlqmoifrij1w5

{
 "scope": "store/cart/*",
 "destination": "https://ortto-commerce.loca.lt/api/cart",
 "is_active": true
}

###
DELETE http://localhost:3000/api/product
Content-Type: application/json
